# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e66088fcb972a841801a8079d73796623d22fa29ec3d3e237de0245bddede66df423c41b704d8603f48fbffb4ac735037141e61120d070c1baa5a3ea08b0ac31
  facebook_app_id: 632739430215658
  facebook_app_secret: 2406b5f4d3c4a722e6ab9f7114ac203f
  twitter_app_id: tNNVrW8kUyeP5SFo29B1iUuew
  twitter_app_secret: zUNXJHIu8XqRviuhC2jqNskEG1huaFomsS8bQL5yyzlu9NFa46

test:
  secret_key_base: bdec3366e09d60d64a60ce97c62e3c8cdc3c9d5c7314f644cdf623e554fb8d67fb1c8caefab540972e8a5fb22f775354d6e2b5424e15eabe5fa6c54e62361af9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>
